### ISSUE TITLE
.sqlfluff config file location

### ISSUE THREAD

**Issue by robertoash** [sqlfluff/vscode-sqlfluff#38]
Hi!

This is more of a question than an issue. According to [SQLFLuff documentation](https://docs.sqlfluff.com/en/stable/configuration.html#nesting), there are several places where SQLFLuff will look for config files. One of them is "It will look for the same files in every subdirectory between the current working dir and the file directory".

Now, I can't figure out what my current working directory is when using the sqlfluff extension. I have changed the cwd of VSCode's Terminal (like this `"terminal.integrated.cwd": "/Users/PargAsh/Work"`) but it doesn't lint according to a config file placed between that directory and the directory of the file being linted. So maybe the VSCode Terminal's cwd is not the same as the SQLFLuff extension's cwd?

There is a specific setting for Python linting (`"python.linting.cwd": ""`) but not for SQLFluff as far as I know.

I would appreciate any help!

**Comment by tunetheweb** [comment]
I think the wording could be improved here, as it means the working directory of the SQL file.

For example if you have a `/project/subproject/file.sql` file, and let's say you are in the `/user/tunetheweb` directory.

And let's say you run the following command: `sqlfluff lint /project/subproject/file.sql`
Or even the following if you want to lint the whole directory: `sqlfluff lint /project/subproject/`

It will look for .sqlfluff in the following locations:

```
/project/subproject/
/project/
/
```

Until it finds one (can't remember if it uses multiple ones with the nearer one overriding previous config, or just uses the first one it finds?).

It will not use `/user/tunetheweb/.sqlfluff` because that is not in the hierarchy of the sql file being linted. So doesn't really use the current working directory of where the command was kicked off from.

Does that make sense?

**Comment by robertoash** [comment]
Yes! That makes sense.

But in that case, I can't figure out why the config file wouldn't be picked up. The SQL file is located here: `/Users/PargAsh/Work/Temp/Looker/conversion.sql`

If I put the file here it works and it is linted according to the config: `/Users/PargAsh/`. As I've understood it, this works because it the "home" directory is one of the defaults (No. 2 in [the documentation](https://docs.sqlfluff.com/en/stable/configuration.html#nesting))

If I put the file here it is **NOT** linted according to the config: `/Users/PargAsh/Work/` and I would expect it to work.

Or have I misunderstood something?

**Comment by tunetheweb** [comment]
I would expect that to work too, unless there is another, closer file in the tree (e.g. in `/Users/PargAsh/Work/.sqlfluff`), but in that case I would have expected it to impact your first test too.

However missed that this was for the vs-code extension rather than regular old SQLFluff, so not sure if that works differently as I have not used it.

**Comment by puetsch** [comment]
Putting the `.sqlfluff` into my home directory `~` worked for me.

**Comment by yingyingqiqi** [comment]
I found that exclude_rules did not work when setting config=.sqlfluff configuration file in vscode-sqlfluff. Below are some troubleshooting methods I have summarized: 
1. Check if vscode-sqlfluff has configured sqlfluff.config. 
2. If there is a default configuration file, please refer to the [documentation](https://docs.sqlfluff.com/en/stable/configuration.html#nesting). If so, set "sqlfluff.ignoreLocalConfig" to true to prevent loading errors.
3. Confirm whether vscode-sqlfluff has configured "sqlfluff.excludeRules": ["TMP", "rules"] or "sqlfluff.codeActions.excludeRules.workspace" or "sqlfluff.codeActions.excludeRules.global". Please set all of them to “sqlfluff.codeActions.excludeRules.workspace”:false or “sqlfluff.excludeRules”: []. (Reason: To prevent running sqlflluf fix while using the parameter --exclude-rules "TMP" --config ./. Sqlfulff, then exclude_rules will only take effect with --exclude-rules TMP).
Hope it's helpful for you.
