### ISSUE TITLE
Settings: `executablePath` does not support VSCode variables

### ISSUE THREAD

**Issue by wong-codaio** [sqlfluff/vscode-sqlfluff#58]
**Problem**
`executablePath` config does not support VSCode variables. ([List of VSCode config variables](https://code.visualstudio.com/docs/editor/variables-reference))

**Steps to replicate**
Assumption: `${workspaceFolder}` is set to `/User/<user>/code` for this project.

1. Launch VSCode, install SQLFluff plugin.
2. Edit VSCode settings
3. Set `sqlfluff.executablePath` to full path to a SQLFluff executable. (See below)
   * Example: `"sqlfluff.executablePath": "/Users/<user>/code/.venv/bin/sqlfluff"`
4. Verify that SQLFluff is able to run.
5. Update `sqlfluff.executablePath` to reference `${workspaceFolder}` instead of having a full path.
   * Example: `"sqlfluff.executablePath": "${workspaceFolder}/.venv/bin/sqlfluff"`

**Expected**
SQLFluff continues to work.

**Actual**
SQLFluff fails to lint, due to executable path is not found.

**Comment by AdilYakubov** [comment]
was facing the same issue today. setting an absolute path to executable helped in my case.

**Comment by RobertOstermann** [comment]
It might be a week or two until I get around to it, but I should be able to include support for the VSCode config variables with with the executablePath configuration in the next release version. For now, the workaround is to set the absolute path, using the workspace settings instead of user settings might help as well.

**Comment by RobertOstermann** [comment]
This should be fixed in v0.0.8
