### ISSUE TITLE
Feature request: vscode Actions

### ISSUE THREAD

**Issue by Luttik** [sqlfluff/vscode-sqlfluff#67]
There are two scenario's where the use of vscode actions are extremely usefull:
1. Running sqlfluff agains the entire project and registering the issues in vscode such that they are shown in the problems tab 
![image](https://user-images.githubusercontent.com/6634187/196720701-95694cd2-3f55-4dc8-8760-d8463668b459.png)
2. Running sqlfluff fix against the current file, currently there is the option to enable it automatically, but this can result in issues when you keep typing. Therefore, it is probably bad practice to keep that option enabled which, in turn, calls for another well-integrated option to run fix from within vscode.

**Comment by RobertOstermann** [comment]
In v0.1.6 I have added the commands `sqlfluff.lint`, `sqlfluff.lintProject`, and `sqlfluff.fix`. I have not added these to the status bar as I don't want to clutter the status bar with commands most people probably will not use. And the `sqlfluff.fix` command essentially just calls the `Format Document` command so I am not sure how much since it actually made for me to add it.

I have also made the linter run against the entire project on startup.

As for adding options to the status bar, I would recommend checking out the `RobertOstermann.better-status-bar` extension or the `seunlanlege.action-buttons` extension which mine is a fork of. The **Better Status Bar** extension will allow you to create a status bar button that calls the given commands, as well as giving more customization of the status bar button than I could give within this SQLFluff extension.
